appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

privacy_pack: true

site_type: Person

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# # TODO
# search:
#   provider: wowchemy
#   algolia:
#     app_id: ''
#     api_key: ''
#     index_name: ''
#     show_logo: false

publications:
  date_format: January 2006
  citation_style: apa

# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance


# Contact (edit or remove options as required)


# Localization

date_format: 'Jan 2, 2006'
time_format: '03:04'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: false
diagram: false

copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135


projects:
  post_view: 2
  publication_view: 2
  talk_view: 2

breadcrumb:
  page_types:
    book: true